[pytest]
python_classes = Test* Suite* Test_*
python_files = test_* *_test check_*
python_functions = test_* check_*

markers =
    smoke: smoke Test
    regression: Regression Test
    sanity: sanity Test
    integration: integration Test
    order: mark test execution order
    ui_journey: UI 여정(주요 사용자 흐름) Test

addopts = -rA -v -s